name: Publish MoonLiveView to Hex.pm

on:
  push:
    tags:
      - "v*"

# So only the latest run is executed. Used to avoid concurrency issues.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish moon_live_view library
    runs-on: ubuntu-22.04
    env:
      HEX_API_KEY: ${{ secrets.HEX_ORGANIZATION_COINGAMING_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Erlang/OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 27
          elixir-version: 1.18.0

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install umbrella dependencies
        run: mix deps.get

      - name: Check formatting (umbrella level)
        run: mix format --check-formatted

      - name: Run tests for moon_live_view library
        run: |
          cd apps/moon_live_view
          mix test

      - name: Verify library package can be built
        run: |
          cd apps/moon_live_view
          mix hex.build

      - name: Publish moon_live_view library to Hex.pm
        run: |
          cd apps/moon_live_view
          mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ env.HEX_API_KEY }}

  # Optional: Create GitHub release after successful publish
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-22.04
    needs: publish
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: MoonLiveView v${{ steps.get_version.outputs.VERSION }}
          body: |
            ## MoonLiveView v${{ steps.get_version.outputs.VERSION }}

            This release publishes the moon_live_view library to Hex.pm.

            ### Changes
            - Check the CHANGELOG.md for detailed changes

            ### Installation
            ```elixir
            def deps do
              [
                {:moon_live_view, "~> ${{ steps.get_version.outputs.VERSION }}"}
              ]
            end
            ```
          draft: false
          prerelease: false
